# Generated by Django 4.2.3 on 2023-08-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
