# Generated by Django 4.2.3 on 2023-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_products_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='products',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
